### ISSUE TITLE
A few things I experienced

### ISSUE THREAD

**Issue by pgrosu** [googlegenomics/api-client-r#10]
Hi Sid,
	
Hope all is going well with the new version.  I just tested a few things:

**1)** So because of how [oauth-cache.R](https://github.com/hadley/httr/blob/26d986de55c2142e91921a1fd94ad01311e6ebf0/R/oauth-cache.R) works, the `.httr-oauth` file gets saved in the directory where R is started from.  Would it be possible to add to [authenticate.R](https://github.com/googlegenomics/api-client-r/blob/100fa644af8db2d27746d55c60396bd073a92486/R/authenticate.R) a check to see if the `.httr-oauth` file exists in `~/.store/genomics_r_client/` and if not, then it would initiate the browser authentication and place a copy of the file in `~/.store/genomics_r_client/`?  Otherwise depending on which directory I am in, then I will always have to authenticate via the browser if the file does not exist locally.
	
**2)** When I run the following `getReadData` query I get the following error, and it does not finish the request - the (...) are there to denote that there were many fetches of read data:
	
```
> getReadData(readsetId = "CPHG3MzoCRDRkqXzk7b6l_kB", chromosome ="1", start=100000000, end=101000000)
Fetching read data page
Parsing read data page
Continuing read query with the nextPageToken: EjBDaGhEVUVoSE0wMTZiME5TUkZKcmNWaDZhemRpTm14ZmEwSVNBVEVZOUtPUE1DZ0EYAiDM0JvNCw
...
Fetching read data page
Parsing read data page
Continuing read query with the nextPageToken: EjBDaGhEVUVoSE0wMTZiME5TUkZKcmNWaDZhemRpTm14ZmEwSVNBVEVZN2FlUE1DZ0EYAiDM0JvNCw
Fetching read data page
Parsing read data page
Continuing read query with the nextPageToken: EjBDaGhEVUVoSE0wMTZiME5TUkZKcmNWaDZhemRpTm14ZmEwSVNBVEVZOHF1UE1DZ0EYAiDM0JvNCw
Fetching read data page
Parsing read data page
Error in elementType(x) :
  error in evaluating the argument 'x' in selecting a method for function 'elementType': Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
>
```

**3)** If I interrupt (via Ctrl-C) a `getReadData` request because I would like to start a different one, I can't seem to perform another request after that:

```
> getReadData(readsetId = "CMvnhpKTFhD04eLE-q2yxnU", chromosome ="1", start=100000000, end=101000000)
Fetching read data page
Parsing read data page
Continuing read query with the nextPageToken: Ei9DaGREVFhadWFIQkxWRVpvUkRBMFpVeEZMWEV5ZVhodVZSSUJNUmlQMU5jdktBRRgCIIGy8rQI
Fetching read data page
Parsing read data page
Continuing read query with the nextPageToken: Ei9DaGREVFhadWFIQkxWRVpvUkRBMFpVeEZMWEV5ZVhodVZSSUJNUmpxNU5jdktBQRgCIIGy8rQI
^C
>  getReadData(readsetId = "CMvnhpKTFhD04eLE-q2yxnU", chromosome ="1", start=10000000, end=101000000)
Fetching read data page
Error in function (type, msg, asError = TRUE)  :
  easy handled already used in multi handle
```

I would need to exit out of R, and resubmit the new `getReadData` request.

I know this is work in progress, but just wanted to give you a heads up.

Thanks,
Paul

**Comment by deflaux** [comment]
Paul, thank you for this feedback.  We're breaking these down into smaller tasks.
