### ISSUE TITLE
submit this package to BioConductor

### ISSUE THREAD

**Issue by deflaux** [googlegenomics/api-client-r#28]
This package is still very much a work in progress, but it will be great to get it polished and ready for BioConductor!  It needs to be run through a linter also to make sure the style is consistent, per #18

**Comment by deflaux** [comment]
This was completed by @siddharthab !

It will be included in the [April 17 release](http://www.bioconductor.org/developers/release-schedule/) of BioConductor.

**Comment by ttriche** [comment]
Don't forget to send an announcement to BioC-devel :-)

Nice job and congratulations!

--t

**Comment by pgrosu** [comment]
Big Congrats Sid and Nicole!  This is HUGE!!!

~p
