### ISSUE TITLE
Problem authenticating with invokeBrowser=F

### ISSUE THREAD

**Issue by jbelsky** [googlegenomics/api-client-r#29]
Hi, I'm trying to authenticate on a server without X11, and whenever I give the "invokeBrowser=F" option I receive the following error message:

Error in authorizer(authorize_url, is_interactive) :
  unused argument (is_interactive)

Thanks for looking into this.

**Comment by deflaux** [comment]
Hello!

I believe you just need `install.packages('httr')` to fix the issue.  Please reopen if that does not resolve it for you.  Thanks!

**Comment by jbelsky** [comment]
Thanks, that was it!  Apologies, I should have done a better job searching for that error, it's been documented elsewhere as well.
